### PR TITLE
Fix coq-metacoq-template.8.17.dev

### PR DESCRIPTION
**Pull request by liyishuai**
Current failure is caused by:
- [ ] MetaCoq/metacoq#1022

### CODE REVIEW

**Comment by liyishuai** [comment]
The CI of #2893 should have complained that coq-metacoq-template-pcuic cannot compile. Maybe need a different timeout  strategy.

**Comment by liyishuai** [comment]
Maybe worth merging asynchronously from MetaCoq/metacoq#1023.

**Comment by silene** [comment]
> The CI of #2893 should have complained that coq-metacoq-template-pcuic cannot compile. Maybe need a different timeout strategy.

It did complain. Unfortunately, when there is a timeout, one has to go and read the logs to check whether the timeout is hiding a real compilation error. I suppose we could set the variable `RUNNER_SCRIPT_TIMEOUT` to something like `150m`, so that the cumulative time of `before_script` and `script` does not exceed 3 hours, and then have an `after_script` that checks whether there was an actual compilation failure and reports it more prominently in the logs.

**Comment by liyishuai** [comment]
Now passes CI.
Propose merging for now, and reverting c292c3bb84817a051f93947631d0580b9cc9e740 after the compatibility issue gets fixed.
